kipr/libwallaby

CMakeLists.txt
include/wallaby/battery.h
include/wallaby/battery.hpp
src/battery.cpp
src/battery_c.cpp
src/wallaby_p.cpp
src/wallaby_p.hpp
src/wallaby_regs_p.hpp
tests/battery_test.c

This initial version can link a C program against the C++ library and cross-compile it for the new controller.   
The power_level() function currently returns volts. We'll need a conversion to battery capacity.

[RFR] Initial check-in, with a battery power level demo

---

CMakeLists.txt
include/wallaby/digital.h
include/wallaby/digital.hpp
src/digital.cpp
src/digital_c.cpp
src/digital_p.cpp
src/digital_p.hpp
src/wallaby_p.cpp
src/wallaby_p.hpp
tests/battery_test.c
tests/led_test.c

Adding digital in/out interface with pull-up control.
This required adding the ability to write specific values to the co-processor, where previously the library was read-only.

[RFR] Digitals

---

CMakeLists.txt

Just cleaning the CMake file up and making it less work to add future source files.

[RFR] CMake: glob source files

---

CMakeLists.txt
src/wallaby_p.cpp
tests/comm_speed_test.c

[RFR] Comm speed

---

CMakeLists.txt
include/wallaby/analog.h
include/wallaby/analog.hpp
src/analog.cpp
src/analog_c.cpp
src/analog_p.cpp
src/analog_p.hpp
tests/analog_test.c

Adding library functionality to read analog sensors and check/modify their pull-ups.

[RFR] Analogs

---

include/wallaby/gyro.h
include/wallaby/gyro.hpp
src/gyro.cpp
src/gyro_c.cpp
src/gyro_p.cpp
src/gyro_p.hpp
tests/imu_test.c

[RFR] Adding gyro functions

---

include/wallaby/magneto.h
include/wallaby/magneto.hpp
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/magneto.cpp
src/magneto_c.cpp
src/magneto_p.cpp
src/magneto_p.hpp
tests/imu_test.c

[RFR] Adding magnetometer functions

---

include/util.hpp
include/wallaby/compat.hpp
include/wallaby/util.h
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/compat.cpp
src/time_p.cpp
src/time_p.hpp
src/util.cpp
tests/analog_test.c
tests/battery_test.c
tests/imu_test.c
tests/led_test.c
tests/servo_test.c

This provides ``msleep()`` which lets me use the delay function for tests that the students will be using.

[RFR] Adding util.h for timing functions

---

include/wallaby/create.h
include/wallaby/create.hpp
include/wallaby/create_codes.h
include/wallaby/util.hpp
include/wallaby/vtable.h
src/create.cpp
src/create_c.cpp
src/nyi.cpp
src/nyi.h

Moving create functions and vtable stuff over from libkovan

[RFR] Adding create functions from libkovan

---

CMakeLists.txt
include/wallaby/ir.h
include/wallaby/ir.hpp
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/ir.cpp
src/ir_c.cpp
tests/ir_test.c

Adding infrared functions for backwards compatibility.  Also, a test program... mostly to check that the functions/library can be linked against.

[RFR] infrared

---

CMakeLists.txt
include/wallaby/button.h
include/wallaby/wait_for.h
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/button.cpp
src/button_c.cpp
src/wait_for.cpp
tests/button_test.c

[WIP] Button test

---

CMakeLists.txt
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/create.cpp
tests/create_test.c

Updating the device path and baud rate.  Adding a test program.

[RFR] New creates

---

tests/create_test.c

``create_connect()`` was probably a decent test of 2-way communication, but now I am using ``get_create_distance`` and ``get_create_total_angle()`` as well.

[RFR] Monitoring distance and angle with the create test

---

src/wallaby_p.cpp

Switched from port SPI0 to SPI1

[RFR] Using /dev/spidev2.0 now for the co-processor

---

src/battlehill_p.cpp

This lets us close our libwallaby programs with Ctrl-C again.

[RFR] Set auto exit

---

src/battlehill_p.hpp

Fixing http://kipr-redmine.bitnamiapp.com/redmine/issues/32

[RFR] Swapping forwards and backwards for the motors

---

src/battlehill_p.cpp
tests/servo_test.c

For consistency with the Link/Kovan

[WIP] Scaling up servo_test.c for 11-bit servo values

---

src/battlehill_p.cpp

So we can stop motors and servos.  (later we will stop create robots too)

[RFR] Adding sig int handler for battlehill

---

src/analog_p.cpp
tests/analog_test.c

Using 12 bit values as a default.

[RFR] Fix adc scaling

---

src/wallaby_p.cpp
src/wallaby_p.hpp

Turns out is is tricky to handle the deadlock that happens with our motor/servo/create cleanup code...

[RFR] Clean exit

---

include/wallaby/gyro.hpp
include/wallaby/magneto.hpp

So they can be included in botui.

[RFR] Make gyro and magnetometer inherit Sensor

---

src/battery_p.cpp

The next step should be a piecewise linear function.

[RFR] Simple linear battery capacity curve for testing

---

include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/accel_p.cpp
src/battery_p.cpp
src/botball_c.cpp
src/gyro_p.cpp
src/magneto_p.cpp
src/wallaby_p.cpp
src/wallaby_p.hpp

* twelve bit IMU  (downscaling)
* fixing writeRegister32b that was affecting motor goals and clearing motor position.

[RFR] Libwallaby v9

---

src/botball_c.cpp

* wait_for_light is more consistent in de-bouncing now
* wait_for_light refers to the 'R' button during user instruction

[RFR] libwallaby for v10 update

---

src/battery_p.cpp

…  and making linear battery capacity curve more clear

[RFR] Switching to LiFePO4 battery voltage range

---

include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/botball_c.cpp
src/display_c.cpp
src/servo_p.cpp

* Include console functions in wallaby headers

[RFR] Update 15

---

include/wallaby/button.h
include/wallaby/button.hpp
include/wallaby/button_ids.hpp
include/wallaby/camera.hpp
include/wallaby/create.hpp
src/button.cpp
src/button_c.cpp
src/button_p.cpp
src/button_p.hpp
src/camera.cpp
src/create.cpp
src/wallaby_p.cpp
src/wallaby_regs_p.hpp

[RFR] Update 17

---

include/wallaby/accel.h
include/wallaby/analog.h
include/wallaby/battery.h
include/wallaby/button.h
include/wallaby/camera.h
include/wallaby/digital.h
include/wallaby/gyro.h
include/wallaby/magneto.h
include/wallaby/motors.h
include/wallaby/servo.h
src/create.cpp
src/motor_p.cpp
src/servo_p.cpp
src/wallaby_p.cpp
src/wallaby_p.hpp

Includes:
* shut_down_in issues.
* bmd() never returning bug
* documentation fixes

[RFR] Update 18

---

bindings/wallaby.i

Include the C camera interface in the python wallaby wrapper

[RFR] Update 19

---

include/wallaby/camera.h
include/wallaby/camera.hpp
src/camera.cpp
src/camera_c.cpp
tests/camera_speed_test.c

I was working with PS3 Eye cameras, but we decided to go with Logitech cameras.

[RFR] Support new cameras

---

doxygen/Doxyfile
doxygen/Doxyfile++
include/wallaby/camera.h
src/camera_c.cpp

Shorter function for new camera.
Updating doxygen project version from 1 to v23 to match controller firmware version.

[RFR] open_camera_black()

---

include/wallaby/compass.h
include/wallaby/compass.hpp
include/wallaby/wallaby.h
include/wallaby/wallaby.hpp
src/compass.cpp
src/compass_c.cpp
src/compass_p.cpp
src/compass_p.hpp
tests/compass_test.c

Dr. Andrew H. Fagg and Twister Robotics provided a method of calibrating the magnetometer/compass in the Wallaby.

[RFR] Adding compass code and test program

---

src/create_c.cpp

Revert "Fix create_spin_block"

---

src/motor_p.cpp

Revert "Fixed get_motor_bemf_vel"

---

src/gyro_p.cpp

The data coming out of this input seems to still have an accuracy problem but it is decently precise. 
You can probably use the gyro in this state to make a pretty good gyroscope library/function set but we need to figure out where that slight inaccuracy is coming from. 
The output seems to have a spike every now and then but I can't find the cause just yet.

Fixed gyroscope to read high and low registers

---

src/botball_c.cpp

A pull request got merged that removed this because it was from an earlier point in the master branch. 
This is putting the wait_for_light function back that wasn't intended to be removed.
I cloned this branch, built it, and then tested the wait for light function and it is working on my Wombat in the lab.

Putting the fixed version of wait_for_light back

---

.github/workflows/cmake_build.yml
.github/workflows/main.yml
README.md

Using a github action code is automatically compiled using CMake any time there is a commit. 
A badge has also been added to the README as a quick visual.

Start of Continuous Integration 

---

.gitignore

Fixes #133 by adding the `doc` folder to `.gitignore`

Add `doc` folder to `.gitignore`

---

src/gyro_p.cpp

The IMU was not being put through a setup process before trying to take data.
I updated the firmware to do that setup process and this is the libwallaby change relevant to match that.
For some reason the high register is all that is necessary, I think it's because we are using the 16 bit read function so it automatically pulls the low register with it.

Gyroscope fix (wombat firmware update)

---

src/wallaby_p.cpp

This PR sends multi-byte register updates in batches instead of individually. So writing a 32 byte register results in a single `postMessage()` to the main thread, instead of four uncorrelated `postMessage()s`.
Related to kipr/Simulator#115 and should be merged together.

[JS] Send register updates in batches

---

src/motor_p.cpp

Fixed: https://github.com/kipr/libwallaby/issues/137

Capping motors at 1500

---

.gitignore
CMakeLists.txt
include/kipr/create.h
include/kipr/create.hpp
include/wallaby/create.h
include/wallaby/create.hpp
install
src/create.cpp
src/create_c.cpp

load and play songs on the create

---

CMakeLists.txt
src/UDPVideo.cpp
src/wpa_ctrl/common/common.h
tests/tello_camera_test.c
tests/tello_swarm_test.c

Fixes various build issues when building libwallaby for the Simulator. This needs review from someone familiar with the recently added Tello support

Fix build issues when compiling for emscripten/Simulator

---

src/wallaby_p.cpp

Remove conflict markers missed in a previous PR

Remove conflict markers

---

module/core/protected/kipr/core/platform.hpp
module/core/src/device/wombat/wombat_device.cpp

fix syntax errors and unique pointer errors

---

module/camera/protected/kipr/camera/channel_impl.hpp
module/camera/public/kipr/camera/channel.hpp
module/camera/src/camera.cpp
module/camera/src/camera_c.cpp
module/camera/src/channel.cpp
module/camera/src/channel_impl.cpp
module/camera/src/channel_p.hpp
module/camera/src/image.cpp

(to be merged into `refactor`, not `master`)
- Expose `Channel` publicly since it's returned from the public camera interface
- Fix bug in `Image` where data was always null

[refactor] Make `Channel` public + Fix Image bug
