- src/battery.cpp
- src/digital_p.cpp
- src/wallaby_p.cpp
- src/wallaby_p.hpp
Adding and using new functions for reading and writing to registers that occupy  more than 8 bits with a single call.  This is faster than doing it one at a time and gets us closer to atomic updates.
> [RFR] New read/write functions for 16 and 32 bit registers

- include/wallaby/button.h
- include/wallaby/button.hpp
- include/wallaby/button_ids.hpp
- include/wallaby/export.h
- include/wallaby/sensor.hpp
- src/button.cpp
- src/button_c.cpp
- src/button_p.cpp
- src/button_p.hpp
The actual implementations in ``src/button_p.cpp`` are not yet done.  This code allows user programs to compile against libwallaby if they are using buttons and lays out most of the code needed  for buttons.
> [RFR] Checking in Button API and related export/sensor code

- CMakeLists.txt
- include/wallaby/audio.h
- include/wallaby/wallaby.h
- src/audio.cpp
- tests/audio_test.c
Adding audio.h with ``beep()``
It doesn't seem to work on the new controller... but speaker-test is the only program we have gotten to work so far and it took a lot of fiddling with alsa-mixer.  Another possibility is it is due to the screen/terminal session.
> [RFR] Audio

- src/motors_p.hpp
This probably got swapped on the firmware side... but I'm going to fix it here.
> [RFR] Fix enum mismatch for MAV

- src/digital_c.cpp
This changes fixes polarity so that ``digital(int port)`` matches ``get_digital_value(int port)``  where the pins are normally at ``0`` and a button press results in a ``1``
> [RFR] Fixing digital in polarity for digital() call

- src/battlehill_p.cpp
copy-paste error which was keeping the servos enabled
> [RFR] Fixing servo disable

- include/wallaby/graphics_key_code.h
It came from libaurora...  nothing seems to be using it.
> [RFR] Removing KeyCode hash that has been causing errors in botui

- src/accel.cpp
The C++ side was returning the z acceleration as y.
> [RFR] Fixing AccelY mapping in C++ interface

- src/motor_p.cpp
``get_motor_done()`` was spamming a debug message and it wasn't very helpful.
> [RFR] Removing get_motor_done() spam

- src/compass_p.cpp
We have renamed ``imu_set_compass_params`` to ``set_compass_params``
> [RFR] Fixing function name in compass calibration output

- src/create_c.cpp
In the documentation and the C code. In C++ Create::turn takes the angle, then speed. In create_spin_block(), the parameters are reversed. This issue is present in all supported versions of libwallaby, as well as the documentation and generated python code.
> Fix create_spin_block

- src/motor_p.cpp
get_motor_bemf_vel read 32b insead of 16b. Furthermore it only has High / Low.
> Fixed get_motor_bemf_vel

- include/wallaby/camera.hpp
- src/botball_c.cpp
- src/camera.cpp
- src/camera_c.cpp
- src/cap_v4l.cpp
- src/precomp.hpp
This patch adds two files taken from opencv v4.0.  The "select timeout" problem that the wallaby's suffered are the fault of the opencv module and so the fixes had to be applied to this module and the the corrected module was incorporated by using c++ overrides.
The "select timeout" problem was also fixed for the white camera as well.
Additionally, the camera delay problem for the black camera was resolved by passing back the most recent frame.
> This patch recovers from "select timeout" errors and reduces the camera delay

- src/camera.cpp
- src/cap_v4l.cpp
The Camera::Device::close() released the capture object, which was
also done in the destructor for Camera::Device as well. Could not
remove this action from the close method becase the user progam
calles this function via a different path and multiple calls
could result in objects not being freed prpperly.
This patch also ensures that the VideoCapture_K can tbe constructed
with either a camera number or a path.
> Fix double release (Resolves #107 Camera live crashes botui)

- src/camera.cpp
- src/camera_c.cpp
- src/cap_v4l.cpp
- tests/camera_speed_test.c
I have tested the Wombat and find that it can easily support 640x480, which is HIGH_RES.
FPS is set at 15, could go higher but this moderates the load on the CPU's and this rate is adequate for botball.
camera_speed_test has been modified to test all three resolutions.
> Set HIGH_RES as the Wombat camera default

- src/wallaby_p.cpp
Currently, running the user program blocks the web worker, preventing the worker from receiving any register updates from the simulator (like sensor updates). This PR adds `emscripten_sleep(0)` before any register read, briefly yielding control to the event loop and allowing it to process updates.
> [emscripten] Return control to JS before reading registers

- CMakeLists.txt
- src/camera.cpp
- src/camera_c.cpp
- src/camera_c_p.cpp
- src/camera_c_p.hpp
- src/cap_v4l.cpp
- src/channel_p.cpp
- src/channel_p.hpp
- src/motor_p.cpp
- src/wallaby_p.cpp
- tests/QRcode_test.c
- tests/aruco_test.c
- tests/bounding_box_test.c
- tests/camera_speed_test.c
Resolves #130 by adding emscripten support to `master`. Previously we were maintaining a separate `emscripten` branch for the simulator, which was quickly becoming unmanageable.
Main changes:
- Conditional logic for reading/writing registers when targeting emscripten (controlled by new CMake option: `emscripten`)
- Conditional compilation of camera-related files to allow building without vision support (controlled by new CMake option: `with_vision_support`). This includes "disabling" tests that depend on vision support. When building without vision support, those tests print out a warning
- I went with conditional-compilation directives for this to stay consistent with other parts of libwallaby. But it kind of litters source files with `#ifdef`s. Might consider a separate issue/PR to …
> Add emscripten support for simulator

- src/wallaby_p.cpp
Fixes kipr/Simulator#117 by yielding to the event loop before writing register values, allowing the worker to catch up on pending "set register" requests.
This fixes a bug where libwallaby would write to a register, but the value wouldn't be sent to the simulator because libwallaby thought the value was unchanged. Really the value *was* changed, but libwallaby didn't know about it yet.
> [JS] Catch up on pending register values before writing registers

- src/wallaby_p.cpp
Update the emscripten JS functions for the new `SharedArrayBuffer` support in the simulator. The simulator will use these new functions shortly
> Update emscripten JS functions for SAB support

- CMakeLists.txt
- toolchain/arm-linux-gnueabihf.cmake
There's still problems w/ cross compiling (since jessie is older than buster and lacks the current libs)
Library problems (checkmark = fixed)
-[x] w/o static linking libstdc++, there's a problem with unfound libstdc++ version GLIBCXX_3.4.26
-[] can't find the right library, but there's problem with version `GLIBC_2.29' not found
> have the correct architecture

- module/motor/protected/kipr/motor/command.hpp
- module/motor/src/command.cpp
Adding this allows the project to build on a Wombat.
> Adding stdexcept because std::out_of_range is used in the .cpp

- module/camera/public/kipr/camera/image.hpp
- module/camera/src/image.cpp
(to be merged into `refactor` branch, not `master`)
Implement assignment operator in `Image`. Since `Image` has a move constructor, the default assignment operator gets deleted. So we have to implement our own assignment operator to support usage like:
```
m_image = kipr::camera::Image();
```
> [refactor] Implement assignment operator in Image

- binding/python/CMakeLists.txt
* use correct link flag to prevent error
* remove redundant line since `kipr_python` is already a shared library, meaning it already is PIC
When building libwallaby with python bindings and camera module enabled, the following error occurs:
> Link Patch

- module/accel/public/kipr/accel/accel.h
- module/accel/src/accel_p.cpp
- module/botball/src/botball_c.cpp
- module/gyro/public/kipr/gyro/gyro.h
- module/gyro/src/gyro_p.cpp
When setting up our robot for the tournament, I noticed that calibrating the gyro and accelerometer took too long. So, I made changes to speed up the calibration process to just 500 milliseconds. I also fixed a problem where calling the gyro calibration method multiple times would add bias, affecting the accuracy of the low pass filter.
We also found that in the wait for light, a camera flash to trigger the light threshold caused the robot to wait longer than necessary. To solve this, I made the robot check the light level continuously after the flash. As soon as the light level drops below the threshold, indicating the end of the flash, the robot tries again without waiting the full two seconds.
> Minor changes to calibration functions as well as wait_for_light

- module/botball/src/botball_c.cpp
Apologies for the inconvenience, but after updating and compiling libwallay, I realized that I forgot to include the commit in the pull request where I corrected a missing semicolon. The issue occurred in the botball module within the wait_for_light function, which I recently modified and merged successfully. Unfortunately, this merge introduced an error that prevents the entire module from compiling - specifically, the semicolon commit I forgot to push onto github and therefore wasn't included in my pull request.
> Fixed missing semicolon from previous pull request

- module/core/src/device/wombat/wombat_device.cpp
Based on the discord thread, I finally fixed the dma de-synchronized issue.
The problem was that the access to the write and read buffers wheren't synchronized properly. The transfer method did some locking, but this wasn't enough.
Now the whole class locks itself when writing to a buffer or reading from it. making sure there are no threads accessing the same buffer at the same time, causing this weird issue.
Sorry for these many changes, my linter reformatted the file for some reason.
The code used to test if de-synchronized error has been fixed:
```c++
#include "kipr/wombat.h"
void manual_move_motor_to_position(int port, int position) {
clear_motor_position_counter(port);
while (get_motor_position_counter(port) <= position) {
motor(port, 100);
msleep(10);
}
}
int main() {
auto thread = …
```
> Fixed DMA de-synchronized when using threads
